services:

  db-auth:
    image: postgres:16.2
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: postgres
      POSTGRES_DB: smart-home-auth-service

  db-notification:
    image: postgres:16.2
    restart: always
    shm_size: 128mb
    ports:
      - '5434:5432'
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: postgres
      POSTGRES_DB: smart-home-auth-service

  db-smart-home:
    build:
      context: .
      dockerfile: ./smart-home-service/db/Dockerfile
    image: smart-home-postgres:16.2-pgvector
    restart: always
    shm_size: 128mb
    ports:
      - '5433:5432'
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: postgres
      POSTGRES_DB: smart-home-smart-service
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
