"""change field in device

Revision ID: 2459d3356b2d
Revises: 8001b91f5d0e
Create Date: 2025-05-19 23:29:22.658221

"""

from alembic import op
import sqlalchemy as sa

revision = "2459d3356b2d"
down_revision = "8001b91f5d0e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices", sa.Column("full_address", sa.String(), nullable=True)
    )
    op.drop_column("devices", "ip_address")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "devices",
        sa.Column(
            "ip_address", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("devices", "full_address")
    # ### end Alembic commands ###
