"""add new field Face

Revision ID: 57fc441d57e2
Revises: 7a846ba210c0
Create Date: 2025-05-20 18:01:55.116990

"""

from alembic import op
import sqlalchemy as sa

revision = "57fc441d57e2"
down_revision = "7a846ba210c0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_faces_name", table_name="faces")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_faces_name", "faces", ["name"], unique=True)
    # ### end Alembic commands ###
