"""change field

Revision ID: d57257dfb46f
Revises:
Create Date: 2025-05-18 14:26:58.804928

"""

from alembic import op
import sqlalchemy as sa

revision = "d57257dfb46f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "home",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("invited_users_ids", sa.ARRAY(sa.Integer()), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("home")
    # ### end Alembic commands ###
