"""add new table - device

Revision ID: 8001b91f5d0e
Revises: 744f682f4a25
Create Date: 2025-05-19 23:22:43.596324

"""

from alembic import op
import sqlalchemy as sa

revision = "8001b91f5d0e"
down_revision = "744f682f4a25"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
