"""change field

Revision ID: 9d5d5eee6e07
Revises: d57257dfb46f
Create Date: 2025-05-18 16:13:24.195756

"""

from alembic import op
import sqlalchemy as sa

revision = "9d5d5eee6e07"
down_revision = "d57257dfb46f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
