"""change_user_password_on_LargeBinary

Revision ID: ae239cd67142
Revises: 2b8ee2343b79
Create Date: 2025-02-27 00:13:26.749849

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import LargeBinary

# revision identifiers, used by Alembic.
revision: str = "ae239cd67142"
down_revision: Union[str, None] = "2b8ee2343b79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "password", type_=LargeBinary, postgresql_using="password::bytea"
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user",
        "password",
        existing_type=sa.LargeBinary(),
        type_=sa.VARCHAR(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
