"""change_user_schema

Revision ID: 2b8ee2343b79
Revises: 18708dff676c
Create Date: 2025-02-26 23:50:25.768681

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2b8ee2343b79"
down_revision: Union[str, None] = "18708dff676c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("profile_id", sa.Integer(), nullable=False)
    )
    op.create_unique_constraint(None, "user", ["profile_id"])
    op.create_foreign_key(None, "user", "profile", ["profile_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_constraint(None, "user", type_="unique")
    op.drop_column("user", "profile_id")
    # ### end Alembic commands ###
