"""change field in session

Revision ID: 55a031b42a97
Revises: e5ec4c129bb4
Create Date: 2025-05-14 22:52:18.333270

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "55a031b42a97"
down_revision: Union[str, None] = "e5ec4c129bb4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "session", "fcm_token", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "session", "fcm_token", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
