"""add_user_id_in_session

Revision ID: b6bc1c426b55
Revises: b5dc43e9a0cc
Create Date: 2025-02-25 22:50:15.138594

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b6bc1c426b55"
down_revision: Union[str, None] = "b5dc43e9a0cc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "session", sa.Column("user_id", sa.Integer(), nullable=False)
    )
    op.create_unique_constraint(None, "session", ["user_id"])
    op.create_foreign_key(None, "session", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "session", type_="foreignkey")
    op.drop_constraint(None, "session", type_="unique")
    op.drop_column("session", "user_id")
    # ### end Alembic commands ###
