"""change_user_schema

Revision ID: 18708dff676c
Revises: b6bc1c426b55
Create Date: 2025-02-26 23:45:55.234915

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18708dff676c"
down_revision: Union[str, None] = "b6bc1c426b55"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("profile_user_id_key", "profile", type_="unique")
    op.drop_constraint("profile_user_id_fkey", "profile", type_="foreignkey")
    op.drop_column("profile", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "profile",
        sa.Column(
            "user_id", sa.INTEGER(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        "profile_user_id_fkey", "profile", "user", ["user_id"], ["id"]
    )
    op.create_unique_constraint("profile_user_id_key", "profile", ["user_id"])
    # ### end Alembic commands ###
