"""ref_uniq_id_session

Revision ID: 54f7d1daccc5
Revises: 9480939e9bba
Create Date: 2025-03-02 00:34:57.166826

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "54f7d1daccc5"
down_revision: Union[str, None] = "9480939e9bba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("session_user_id_key", "session", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("session_user_id_key", "session", ["user_id"])
    # ### end Alembic commands ###
